### ISSUE TITLE
2. Add Two Numbers

### ISSUE THREAD

**Issue by vidhichadha2507** [vidhichadha2507/Leetcode#1]

**Comment by flow6979** [comment]
hey @vidhichadha2507, I want to contribute to this issue. can you please assign this to me?

**Comment by vidhichadha2507** [comment]
> hey @vidhichadha2507, I want to contribute to this issue. can you please assign this to me?

Sure

**Comment by developerHarshRaj** [comment]
Hey @vidhichadha2507 , I want to contribute. Can you please assign this issue to me?

**Comment by flow6979** [comment]
hey @developerHarshRaj, i am already assigned :)
