### ISSUE TITLE
Shuffle String

### ISSUE THREAD

**Issue by aparnamittal** [vidhichadha2507/Leetcode#34]
# Question:
You are given a string s and an integer array indices of the same length. The string s will be shuffled such that the character at the ith position moves to indices[i] in the shuffled string.

Return the shuffled string.

![image](https://user-images.githubusercontent.com/100208233/193454546-bdbac9e3-d933-431e-8a54-02c084f45745.png)

**Comment by aparnamittal** [comment]
@vidhichadha2507 can you assign me this issue under hacktoberfest

**Comment by vidhichadha2507** [comment]
Yes, you can contribute now.
