### ISSUE TITLE
125. Valid Palindrome

### ISSUE THREAD

**Issue by vidhichadha2507** [vidhichadha2507/Leetcode#5]

**Comment by salted0dreams** [comment]
can you  pls describe the issue?

**Comment by flow6979** [comment]
hey @vidhichadha2507, I want to contribute to this issue. can you please assign this to me?

**Comment by vidhichadha2507** [comment]
> hey @vidhichadha2507, I want to contribute to this issue. can you please assign this to me?

You Can now contribute on this issue

**Comment by sampaddey** [comment]
Hey can I contribute to this issue??

**Comment by flow6979** [comment]
Hey @vidhichadha2507 , just a suggestion, as you have already merged my PR for this issue, you can close the issue now.

**Comment by vidhichadha2507** [comment]
> Hey @vidhichadha2507 , just a suggestion, as you have already merged my PR for this issue, you can close the issue now.

Sure
